dist: xenial  # Required for Python >= 3.7.
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
script:
  - python setup.py install
  - pip install py>=1.5  # Required for Python 3.4 test on Travis.
  - python setup.py test
